### ISSUE TITLE
issuer same as audience

### ISSUE THREAD

**Issue by hpatoio** [Spomky-Labs/lexik-jose-bridge#39]
These 2 services : 

``` 
    spomkylabs_lexik_jose_checker_audience:
        class: 'Jose\Component\Checker\AudienceChecker'
        arguments:
            - '%lexik_jose_bridge.encoder.issuer%'
            - true
        tags:
            - { name: 'jose.checker.claim', alias: 'lexik_jose_audience' }
            - { name: 'jose.checker.header', alias: 'lexik_jose_audience' }
```

and 

```
    spomkylabs_lexik_jose_checker_issuer:
        class: 'SpomkyLabs\LexikJoseBundle\Checker\IssuerChecker'
        arguments:
            - '%lexik_jose_bridge.encoder.issuer%'
        tags:
            - { name: 'jose.checker.claim', alias: 'lexik_jose_issuer' }
            - { name: 'jose.checker.header', alias: 'lexik_jose_issuer' 
```

They both receive the same parameter `lexik_jose_bridge.encoder.issuer`. This make impossible to have different values for `audience` and `issuer`.

AFAIK these 2 value can be different. Take for instance JWT token generated by Firebase. According to the doc here https://firebase.google.com/docs/auth/admin/verify-id-tokens the valie for `iss` is 
 `https://securetoken.google.com/<audience>`

I've already fixed this on my local branch but before opening a PR I just wanna know if you agree that we should have different parameters for `audience` and `issuer`
